# This file is *NOT* reloaded automatically when you use 'jekyll serve'.
# If you change this file, you will have to restart the server process.

title: Epidemica
baseurl: ""  # with leading slash, without trailing slash; should be the name of the repo if serving on GitHub Pages; use the empty string (""), not a slash, if you host on root; see https://github.com/github/pages-gem/issues/350
url: https://epidemica.info  # no trailing slash, see https://byparker.com/blog/2014/clearing-up-confusion-around-baseurl/
email: colabo@umassmed.edu
repository: colabobio/epidemica-website
description: Epidemica is a platform for infectious disease research.
lang: en  # set the language of your website with its ISO code in order to improve indexation and automated translation
# twitter_username: colabobio  # associate a Twitter username with this website
github_username: colabobio

collections:
  toplevel:
    output: true
  posts:
    output: true
    permalink: /news/:year/:month/:day/:title/

defaults:  # rather than repeating config in all YAML front matters, use defaults for each type of content you have in your website
  -
    scope:
      path: ""  # means "all files"
    values:
      layout: default
  -
    scope:
      path: toplevel  # despite the property name, this is the name of a collection, not a folder path, so there is no leading underscore
    values:
      layout: default
  -
    scope:
      path: "_posts"
    values:
      layout: post

exclude:
  - .circleci
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
